### ISSUE TITLE
Radiant CMS - Application Error when logging in

### ISSUE THREAD

**Issue by brittanyblair** [radiant/radiant#398]
I've installed the Radiant CMS on my Ruby on Rails app, and the install was (seemingly) successful. However when I navigate to: www.myserver.com/admin, I typed in my username and password, hit the submit button, and get the below error:

> Application error
> 
> Change this error message for exceptions thrown outside of an action (like in Dispatcher setups or broken Ruby code) in public/500.html

Does anyone know why this might be? See the gist of my console log below:

```
> [2016-02-15 06:49:12] WARN  Could not determine content-length of
> response body. Set content-length of the response or set
> Response#chunked = true /!\ FAILSAFE /!\  2016-02-15 06:49:16 +0000  
> Status: 500 Internal Server Error   undefined method `options?' for
> #<Rack::Cache::Request:0x00000003a1a380>
```

**Comment by gomarotec** [comment]
I have the same problem!

=> Ctrl-C to shutdown server
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:8080, CTRL+C to stop
/!\ FAILSAFE /!\  2016-04-06 09:54:14 +0000
  Status: 500 Internal Server Error
  undefined method `options?' for #<Rack::Cache::Request:0x00000004f63ae8>
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:71:in `call!'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:51:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-2.3.18/lib/action_controller/string_coercion.rb:25:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.1.6/lib/rack/head.rb:9:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.1.6/lib/rack/methodoverride.rb:24:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-2.3.18/lib/action_controller/params_parser.rb:15:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-2.3.18/lib/action_controller/session/cookie_store.rb:99:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-2.3.18/lib/action_controller/failsafe.rb:26:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.1.6/lib/rack/lock.rb:11:in `block in call'
    <internal:prelude>:10:in `synchronize'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.1.6/lib/rack/lock.rb:11:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/actionpack-2.3.18/lib/action_controller/dispatcher.rb:106:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rails-2.3.18/lib/rails/rack/static.rb:31:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.1.6/lib/rack/urlmap.rb:47:in `block in call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.1.6/lib/rack/urlmap.rb:41:in `each'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.1.6/lib/rack/urlmap.rb:41:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rails-2.3.18/lib/rails/rack/log_tailer.rb:17:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.1.6/lib/rack/content_length.rb:13:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.1.6/lib/rack/chunked.rb:15:in `call'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.4/lib/thin/connection.rb:53:in `process'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.4/lib/thin/connection.rb:39:in `receive_data'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run_machine'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/eventmachine-1.2.0.1/lib/eventmachine.rb:194:in `run'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.4/lib/thin/backends/base.rb:73:in `start'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.4/lib/thin/server.rb:162:in `start'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.1.6/lib/rack/handler/thin.rb:14:in `run'
    /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rails-2.3.18/lib/commands/server.rb:111:in `<top (required)>'
    script/server:3:in `require'
    script/server:3:in `<main>'

**Comment by jimmckerchar** [comment]
I'm also experiencing this issue. I followed the step-by step guide here >> https://github.com/radiant/radiant/wiki/Installing-on-Ubuntu

but when i try to log in using the username/password configured during installation, i get this in the terminal...

```
 SQL (0.1ms)   SELECT DISTINCT class_name FROM pages WHERE class_name <> '' AND class_name IS NOT NULL
/!\ FAILSAFE /!\  2016-06-21 09:54:12 +0100
  Status: 500 Internal Server Error
  undefined method `options?' for #<Rack::Cache::Request:0x00000005974780>
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:71:in `call!'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/rack-cache-1.6.1/lib/rack/cache/context.rb:51:in `call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/actionpack-2.3.18/lib/action_controller/string_coercion.rb:25:in `call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/rack-1.1.6/lib/rack/head.rb:9:in `call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/rack-1.1.6/lib/rack/methodoverride.rb:24:in `call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/actionpack-2.3.18/lib/action_controller/params_parser.rb:15:in `call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/actionpack-2.3.18/lib/action_controller/session/cookie_store.rb:99:in `call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/actionpack-2.3.18/lib/action_controller/failsafe.rb:26:in `call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/rack-1.1.6/lib/rack/lock.rb:11:in `block in call'
    <internal:prelude>:10:in `synchronize'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/rack-1.1.6/lib/rack/lock.rb:11:in `call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/actionpack-2.3.18/lib/action_controller/dispatcher.rb:114:in `block in call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/actionpack-2.3.18/lib/action_controller/reloader.rb:34:in `run'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/actionpack-2.3.18/lib/action_controller/dispatcher.rb:108:in `call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/rails-2.3.18/lib/rails/rack/static.rb:31:in `call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/rack-1.1.6/lib/rack/urlmap.rb:47:in `block in call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/rack-1.1.6/lib/rack/urlmap.rb:41:in `each'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/rack-1.1.6/lib/rack/urlmap.rb:41:in `call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/rails-2.3.18/lib/rails/rack/log_tailer.rb:17:in `call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/rack-1.1.6/lib/rack/content_length.rb:13:in `call'
    /home/work/.rvm/gems/ruby-1.9.3-p551@radiant/gems/rack-1.1.6/lib/rack/handler/webrick.rb:48:in `service'
    /home/work/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/webrick/httpserver.rb:138:in `service'
    /home/work/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
    /home/work/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/webrick/server.rb:191:in `block in start_thread'
```

thanks

**Comment by ukoloff** [comment]
I found that adding `gem 'rack-cache', '~>1.2.0'` to Gemfile fixes this issue.
